server.port: 9901

spring:
  application:
    name: person-service
  datasource:
    username: root
    password: Am311865186
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/abol

  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9001/eureka}

